###################################################################
# Project information
###################################################################
site_name:        ProGuard
site_description: Optimizer and obfuscator for Java bytecode
site_author:      Guardsquare NV
copyright:        Copyright &copy; 2002-2020 Guardsquare NV

###################################################################
# Options
###################################################################
theme:
  name:       null
  custom_dir: ../buildscripts/mkdocs/material
  logo:       img/proguard.png
  favicon:    img/guardsquare.png
  language:   en
  palette:    blue
  font:
  feature: 

docs_dir: md
site_dir: html

extra_css:
  - css/extra.css

use_directory_urls: false
#strict: true # broken links are errors

###################################################################
# Theme specific
###################################################################
extra:
  #font:
  #  text: 'Droid Sans'
  #  code: 'Ubuntu Mono'
  social:
  - type: 'twitter'
    link: 'https://twitter.com/guardsquare'
  - type: 'linkedin'
    link: 'https://www.linkedin.com/company/guardsquare-nv'
  - type: 'facebook'
    link: 'https://www.facebook.com/guardsquare'
  #feature:
  #  tabs: true

###################################################################
# Extensions
###################################################################
markdown_extensions:
- attr_list
- admonition
- footnotes
- def_list

###################################################################
# Page tree
###################################################################
nav:
- Main:                index.md
- Results:             results.md
- FAQ:                 FAQ.md
- ProGuard Manual:
    - Introduction:    manual/index.md
    - Usage:           manual/usage.md
    - Attributes:      manual/attributes.md
    - Optimizations:   manual/optimizations.md
    - Limitations:     manual/limitations.md
    - Examples:        manual/examples.md
    - Troubleshooting: manual/troubleshooting.md
    - Reference Card:  manual/refcard.md
    - GUI:             manual/gui.md
    - Ant Task:        manual/ant.md
    - Gradle Task:     manual/gradle.md
    - Gradle Plugin:   manual/gradleplugin.md
    - JME WTK:         manual/wtk.md
- ReTrace Manual:
    - Introduction:    manual/retrace/index.md
    - Usage:           manual/retrace/usage.md
    - Mapping File:    manual/retrace/mapping.md
    - Examples:        manual/retrace/examples.md
- License:
    - Overview:        license.md
    - GPL:             GPL.md
    - GPL Exception:   GPL_exception.md
- Downloads:           downloads.md
- Building:            building.md
- Release notes:       releasenotes.md
- Feedback:            feedback.md
