###################################################################
# Project information
###################################################################
site_name:        ProGuard Core
site_description: Documentation for the ProGuard Core library
site_author:      Guardsquare
copyright:        Copyright &copy; 2002-2020 Guardsquare

###################################################################
# Options
###################################################################
theme:
  name: null
  custom_dir: ../buildscripts/mkdocs/material
  logo:       img/logo.png
  favicon:    img/favicon.png
  language:   en
  palette:    blue
  font:
  feature: 

docs_dir: md
site_dir: html

extra_css: 
  #This one overrides the default colors with GuardSquare-like colors
  #- ./extra.css
  #This one provides the CSS for some of the figures in the manual
  #- ./extra2.css

use_directory_urls: false
#strict: true # broken links are errors

###################################################################
# Theme specific
###################################################################
extra:
  #font:
  #  text: 'Droid Sans'
  #  code: 'Ubuntu Mono'
  social:
  - type: 'twitter'
    link: 'https://twitter.com/guardsquare'
  - type: 'linkedin'
    link: 'https://www.linkedin.com/company/guardsquare-nv'
  - type: 'facebook'
    link: 'https://www.facebook.com/guardsquare'
  #feature:
  #  tabs: true

###################################################################
# Extensions
###################################################################
markdown_extensions:
- attr_list
- admonition
- footnotes
- def_list

###################################################################
# Page tree
###################################################################
nav:
- Introduction:        index.md
- Reading classes:     reading.md
- Creating classes:    creating.md
- Editing classes:     editing.md
- Pattern matching:    patternmatching.md
- Analyzing code:      analyzing.md
- License:             license.md
- Release notes:       releasenotes.md

copyright: <hr/>Copyright © 2002-2020 <a href="https://www.guardsquare.com/proguard" target="_blank">Guardsquare NV</a>
